### ISSUE TITLE
Unexpected behavior: automatically assigning a default value of 1 to an array specified as [] when clicking format

### ISSUE THREAD

**Issue by Gidsss** [Gidsss/UwUIDE#290] opened 2024-05-18 06:47 UTC
https://github.com/Gidsss/UwUIDE/assets/88811389/ab83cafc-c298-4a3e-9505-b49d481f9ded

**Comment by am-cid** [comment] 2024-05-18 08:38
This is prolly expected behavior since functionality does not change
cc @HolyShaq please close as not planned if I'm correct

**Comment by HolyShaq** [comment] 2024-05-18 08:41
Gids and I talked, and I feel like it'd be best if we format it the way the user typed the declaration so I'm planning on fixing it.

**Comment by am-cid** [comment] 2024-05-18 17:38
closed #292, closing this

**Closed by am-cid** 2024-05-18 17:38 UTC
